"""Regenerate AGENTS.md from CLAUDE.md, so every coding agent reads the same rules. No game, no network.

CLAUDE.md is the one file people and agents edit. AGENTS.md is the same content under the name other tools
look for (Codex, Cursor, Copilot, Gemini CLI ...), with a short note on top. It is GENERATED: never edit it by
hand, because `tests/test_agents_md.py` fails as soon as the two drift apart.

    python scripts/sync_agents_md.py           # rewrite AGENTS.md (prints whether it changed)
    python scripts/sync_agents_md.py --check   # exit 1 if AGENTS.md is out of date, change nothing
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "CLAUDE.md"
TARGET = REPO / "AGENTS.md"

NOTE = (
    "> **Generated from `CLAUDE.md` by `python/scripts/sync_agents_md.py` - do not edit this file by hand.**\n"
    "> Edit `CLAUDE.md`, run the script, and commit both files together; `python/tests/test_agents_md.py` fails\n"
    "> when they drift. Wherever the text below says \"this file\", it means `CLAUDE.md`. The rules apply to every\n"
    "> coding agent working in this repository, whatever tool it runs in.\n"
)


def render(source_text: str) -> str:
    """AGENTS.md's full text for a given CLAUDE.md: the note goes right under the first heading."""
    lines = source_text.replace("\r\n", "\n").split("\n")
    for index, line in enumerate(lines):
        if line.startswith("# "):
            head, rest = lines[: index + 1], lines[index + 1:]
            break
    else:  # no heading at all: put the note first
        head, rest = [], lines
    while rest and not rest[0].strip():
        rest = rest[1:]
    body = "\n".join(head + ["", NOTE.rstrip("\n"), ""] + rest)
    return body if body.endswith("\n") else body + "\n"


def current(path: Path) -> str | None:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if AGENTS.md is out of date; write nothing")
    args = parser.parse_args()
    wanted = render(SOURCE.read_text(encoding="utf-8"))
    if current(TARGET) == wanted:
        print("AGENTS.md is up to date")
        return 0
    if args.check:
        print("AGENTS.md is OUT OF DATE: run python scripts/sync_agents_md.py and commit it with CLAUDE.md")
        return 1
    TARGET.write_text(wanted, encoding="utf-8", newline="\n")
    print("AGENTS.md rewritten from CLAUDE.md (%d lines)" % wanted.count("\n"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
